name: Dokazovi-fe Master

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Merge Release to Master']
    branches: [main]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    environment: master

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Copy all sources
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install, build, test, lint
        run: npm run assemble
        env:
          CI: false
      - name: Deploy on heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          docker_compose_file: 'docker-compose.prod.yml'
          heroku_apps: '[{"imagename":"dokazovi_fe","appname":"my-own-netflix-shar","apptype":"web"}]'
