name: my-own-netflix deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['Merge Release to Master']
    branches: [main]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    environment: master

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Deploy on heroku
        uses: AkhileshNS/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
